language: cpp

compiler:
 - gcc
 - clang

before_install:
 # we need at least g++-4.7 for c++11 features
 - if [ "${CXX}" = 'g++' ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi;
 # we need at least clang++-3.2 for c++11 features
 - if [ "${CXX}" = 'clang++' ]; then sudo apt-add-repository -y ppa:timchen119/llvm; fi;
 # grab more recent gdal/proj
 - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
 # more recent boost
 - sudo add-apt-repository -y ppa:mapnik/boost
 - sudo apt-get update -y
 # upgrade compilers
 - if [ "${CXX}" = 'g++' ]; then sudo apt-get install -y gcc-4.7 g++-4.7; fi;
 - if [ "${CXX}" = 'clang++' ]; then sudo apt-get install -y clang++; fi;
 - sudo apt-get install -y make libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-python-dev libboost-regex-dev libboost-system-dev libboost-thread-dev python-nose libicu-dev libpng-dev libjpeg-dev libtiff-dev libwebp-dev libz-dev libfreetype6-dev libxml2-dev libproj-dev libcairo-dev python-cairo-dev libsqlite3-dev postgresql-server-dev*
 - wget http://mapnik.s3.amazonaws.com/deps/harfbuzz-0.9.24.tar.bz2
 - tar xf harfbuzz-0.9.24.tar.bz2
 - cd harfbuzz-0.9.24
 - ./configure && make && sudo make install
 - sudo ldconfig
 - cd ../

install:
 - if [ "${CXX}" = 'g++' ]; then export CXX="g++-4.7" && export CC="gcc-4.7"; fi;
 - ./configure CXX=${CXX} CC=${CC} DEMO=False BINDINGS=${BINDINGS} BENCHMARK=${BENCHMARK} CPP_TESTS=${CPP_TESTS} CAIRO=True FAST=True || cat config.log
 - JOBS=1 make

env:
  - TESTS_TO_RUN=python BINDINGS=python CPP_TESTS=false BENCHMARK=false
  - TESTS_TO_RUN=visual BINDINGS=python CPP_TESTS=false BENCHMARK=false
  - TESTS_TO_RUN=cpp BINDINGS=none CPP_TESTS=true BENCHMARK=true

before_script:
 - make test-$TESTS_TO_RUN

script:
 - if [ "${BENCHMARK}" = true ]; then make bench; fi;

notifications:
  irc:
    channels:
      - "irc.freenode.org#mapnik"
    use_notice: true
