sources = """
occi_types.cpp
occi_datasource.cpp
occi_featureset.cpp      
spatial_classesm.cpp      
spatial_classeso.cpp      
""".split()

def build(bld):
    bld.plugin("occi", source=sources, use="mapnik")
